name: Diagnostic CI

on:
  push:
    branches:
      - main

jobs:
  diagnostic-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment
        run: env

      - name: Docker Info
        run: docker info

      - name: Print gcloud version
        run: gcloud version

      - name: Check Bash Version
        run: bash --version

      - name: List all installed packages
        run: dpkg --list
