name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -la

      - name: Build and tag Docker images
        run: |
          docker build -t us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest -f recipe-service/Dockerfile recipe-service/
          docker tag us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}

      - name: Login to Google Artifact Registry
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | docker login -u _json_key --password-stdin https://us-docker.pkg.dev

      - name: Push images to Google Artifact Registry
        run: |
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}
