name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Artifact Registry
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | docker login -u _json_key --password-stdin https://us-docker.pkg.dev

      - name: Build and tag Docker image
        run: |
          docker build -t us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest -f Dockerfile .
          docker tag us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}

      - name: List Docker images
        run: docker images

      - name: Push images to Google Artifact Registry
        run: |
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}

      - name: Print environment and tools version
        run: |
          echo "Testing environment..."
          env
          echo "Checking docker..."
          docker info
          echo "Checking gcloud..."
          gcloud version
