name: Incremental Diagnostic CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment and tools version
        run: |
          echo "Testing environment..."
          env
          echo "Checking docker..."
          docker info
          echo "Checking gcloud..."
          gcloud version
          
      - name: Check JSON Format
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          head -c 100 gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker us-docker.pkg.dev --quiet
        

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker us-docker.pkg.dev --quiet
       
      - name: Test GCloud Authentication
        run: |
          gcloud auth list
        
      - name: Push images to Google Artifact Registry
        run: |
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}
        

