name: CI/CD Pipeline

on:
  push:
    branches: [ main ] 

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      - name: Build and tag Docker image
        run: docker build -t us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest .  

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }} 
          service_account_key: ${{ secrets.GCP_SA_KEY }}  
          export_default_credentials: true

      - name: Print GCP Credentials  # Debugging Step
        run: echo ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet 

      - name: Push image to GCR
        run: docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest  
