name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
          docker build -t us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest -f recipe-service/Dockerfile recipe-service/
          docker tag us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        

      - name: Authenticate GCloud Service Account
        uses: google-github-actions/auth@v0.7.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Verify Credentials are Set
        run: |
            if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
              echo "GCP_SA_KEY is not set."
            else
              echo "GCP_SA_KEY is set."
            fi
        

      - name: Configure Docker for GCR
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://us-docker.pkg.dev
          

      - name: Push image to GAR
        run: |
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:latest
          docker push us-docker.pkg.dev/tu-dublin-ca/recipe-service/recipe-service:${{ github.sha }}
