name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
          docker build -t gcr.io/tu-dublin-ca/recipe-service:latest -f recipe-service/Dockerfile recipe-service/
          docker tag gcr.io/tu-dublin-ca/recipe-service:latest gcr.io/tu-dublin-ca/recipe-service:${{ github.sha }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.tu_dublin_ca }}
          version: 'latest'

      - name: Authenticate GCloud Service Account
        uses: google-github-actions/auth@v0.7.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker europe-west4 --quiet

      - name: Push image to GCR
        run: |
          docker push gcr.io/tu-dublin-ca/recipe-service:latest
          docker push gcr.io/tu-dublin-ca/recipe-service:${{ github.sha }}
